In [1]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf
print(tf.__version__)

TensorFlow 2.x selected.
2.0.0-rc1


In [0]:
import numpy as np
import random
random.seed(42) # not necessary, but may be helpful if you have other code
np.random.seed(42) # not necessary, but may be helpful if you have other code
tf.random.set_seed(42)

In [3]:
data = tf.random.normal((2,2))
print(data)

tf.Tensor(
[[ 0.3274685 -0.8426258]
 [ 0.3194337 -1.4075519]], shape=(2, 2), dtype=float32)


In [0]:
# tf.Tensor(
# [[ 0.3274685 -0.8426258]
#  [ 0.3194337 -1.4075519]], shape=(2, 2), dtype=float32)

In [5]:
d1 = tf.keras.layers.Dense(10)
d1(data)

<tf.Tensor: id=32, shape=(2, 10), dtype=float32, numpy=
array([[ 3.7109971e-01, -2.4235262e-01,  6.5287197e-01, -1.5628605e-01,
        -1.4903258e-01, -2.6508850e-01,  3.9794555e-01,  5.0421464e-01,
        -5.1887747e-04, -4.5579481e-01],
       [ 5.5942553e-01, -3.9983889e-01,  9.5186549e-01, -1.8130748e-01,
        -3.2334584e-01, -5.6916070e-01,  5.2095705e-01,  7.6201010e-01,
         4.7649894e-02, -7.7656138e-01]], dtype=float32)>

In [0]:
# <tf.Tensor: id=32, shape=(2, 10), dtype=float32, numpy=
# array([[ 3.7109971e-01, -2.4235262e-01,  6.5287197e-01, -1.5628605e-01,
#         -1.4903258e-01, -2.6508850e-01,  3.9794555e-01,  5.0421464e-01,
#         -5.1887747e-04, -4.5579481e-01],
#        [ 5.5942553e-01, -3.9983889e-01,  9.5186549e-01, -1.8130748e-01,
#         -3.2334584e-01, -5.6916070e-01,  5.2095705e-01,  7.6201010e-01,
#          4.7649894e-02, -7.7656138e-01]], dtype=float32)>

In [7]:
print(d1.weights[0])

<tf.Variable 'dense/kernel:0' shape=(2, 10) dtype=float32, numpy=
array([[ 0.26571834, -0.02195024,  0.6095181 , -0.35046047,  0.32690102,
         0.55517536,  0.6317974 ,  0.3526116 , -0.21318382,  0.06672621],
       [-0.3371429 ,  0.27908546, -0.53793037,  0.04927605,  0.30390996,
         0.53035516, -0.22673386, -0.46135002, -0.08223355,  0.5668537 ]],
      dtype=float32)>


In [0]:
# <tf.Variable 'dense/kernel:0' shape=(2, 10) dtype=float32, numpy=
# array([[ 0.26571834, -0.02195024,  0.6095181 , -0.35046047,  0.32690102,
#          0.55517536,  0.6317974 ,  0.3526116 , -0.21318382,  0.06672621],
#        [-0.3371429 ,  0.27908546, -0.53793037,  0.04927605,  0.30390996,
#          0.53035516, -0.22673386, -0.46135002, -0.08223355,  0.5668537 ]],
#       dtype=float32)>